# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/app
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache    
  ports:
    - 8080:80
  command:
      sh -c 'python3 app.py'
